### PR TITLE
Support for temporary items

### PR DESCRIPTION
**Pull request by davincho**
Behaviour of inject, filter and isNew implemented as proposed in ticket #197 

There are still some open points such as `DSSave` and `DSCreate`. @jmdobry maybe you can make some comments if I am on the right track.

### CODE REVIEW

**Comment by jmdobry** [comment]
I'm not sure I like the performance implications of storing an array of temporary IDs, and having to search the array on every iteration of the filter callback. What about actually attaching a property to a temporary item itself that marks it as temporary? Or instead of an array of IDs, keep an index of IDs for O(1) lookup times?

**Comment by davincho** [comment]
Yes that make sense. I was thinking about a property for each instance but I did not want to mix data properties and internal properties of an instance. Maybe I missed something - is there a way of hiding an internal property?

**Comment by davincho** [comment]
@jmdobry I am thinking about what would be the best way of replacing the artifical ID with the one returned by the server. Foreign keys of other items referencing the temporary item have to be updated as well.

**Comment by jmdobry** [comment]
I hadn't considered that, I think I'm losing enthusiasm for this feature.

**Comment by davincho** [comment]
Mh too bad - I think this feature could be really helpful. I thought about if it would be possible keeping the original ID (=guid) internally, while exposing the updated Id to the user. Or do you prefer to abandon the feature completely?

**Comment by jmdobry** [comment]
I'm working on this in v3, I'll see if I can find a nice way to back port it.

**Comment by jessehouchins** [comment]
@jmdobry Am i right in thinking that this only handles temporary ids for a specific resource and DOES NOT update relations when the new id is returned from the server?

**Comment by jmdobry** [comment]
Right

**Comment by rgant** [comment]
Is there any documentation for this feature?

Throughout my code when creating new resources I've had to do things like:
```
var newStrategy = DS.createInstance('report_strategies', {reportid: theReport.id, id: ''});
```

But maybe I should have been doing:
```
var newStrategy = DS.createInstance('report_strategies', {reportid: theReport.id}, {temporary: true});
```

I don't see the word "temporary" anywhere when searching the documentation.

**Comment by rgant** [comment]
Seems like that won't work because [resolveId](https://github.com/js-data/js-data/blob/ec1865f8807b98103a2bb6b529ca4b91c3e004a8/src/utils.js#L366) doesn't know about the temporary option and many of promises check for the [id being a string or number](https://github.com/js-data/js-data/search?utf8=%E2%9C%93&q=_snErr) and reject immediately if not. So I guess this doesn't really help.

I'm not finding the documentation I need to understand the whole process of how to create new resources in the real world.

**Comment by jmdobry** [comment]
In V3 records have an [`isNew()`](http://api.js-data.io/js-data/latest/Record.html#isNew) method, which just returns `true` or `false` based on whether the record has a primary key. Records with and without primary keys can be inserted into Collections. Records without primary keys are invisible to certain operations, like `Collection#get(id)`. Collections also have a helper method for retrieving unsaved records from the collection (since they don't have IDs): [`Collection#unsaved()`](http://api.js-data.io/js-data/latest/Collection.html#unsaved)

**Pull request merged**
