### PR TITLE
Added onConflict: 'skip' behavior to Collection/ Simple Store.

### PR DESCRIPTION
**Pull request by kvandelden**
Added onConflict: 'skip' behavior to Collection/ Simple Store.
Added test cases.

### CODE REVIEW

**Comment by jmdobry** [comment]
Is this ready for review?

**Comment by kvandelden** [comment]
Yes.

**Comment by jmdobry** [comment]
Linter and tests needs to to pass (CircleCI and Travis need to go green)

**Comment by jmdobry** [comment]
Fixes #454

**Pull request merged**
