### PR TITLE
Closes #205 Allow preserving fields on DSRevert

### LINKED ISSUE #205: DS#revert should ignore omitted fields
Just as the title says. The docs say:
> Synchronously revert the state of an item to the last time it was saved via an async adapter. Returns the reverted item.

I know it can be interpreted several ways, but I take this to mean revert the item back to the last "true" state, as defined by the external backend. Since the backend is blind to the omitted fields, I'd expect the omitted fields to be... omitted from the state.

In my specific use case, I'm using an omitted field to keep track of whether the user has selected an item. If the user makes a change to the item while it is selected, saves the change to the server, and deselects the item, the next time the user reverts a change, the item will be selected again.

### PR DESCRIPTION
**Pull request by internalfx**

### CODE REVIEW

**Comment by internalfx** [comment]
Ugh, I need to learn how to keep from sending all the commits that aren't pertinent.

**Comment by jmdobry** [comment]
This PR only addresses one of the two use-cases presented in #205 , was that your intention?

**Comment by jmdobry** [comment]
While on 2.x the code should use JSData's utility methods. 3.x would be the place to consider reducing the number of browser-compatible utility methods that are needed.

**Comment by internalfx** [comment]
> This PR only addresses one of the two use-cases presented in #205 , was that your intention?

Kind of, It seemed the array was the most overall useful feature. But it does require you to be more explicit.

If you or @awhitty want the other feature, I would be willing to create another PR later.

**Comment by jmdobry** [comment]
One more thing: can you squash the commits into one?

**Comment by internalfx** [comment]
wow.

wanted to remove `@internalfx 	don't bind functions that dont use 	2adf5c9`

But its from a while ago, and I think you made the same edits....

Tried to "rebase" apparently a bad idea.

I clearly just don't understand git.

**Comment by jmdobry** [comment]
Maybe just save your edits to `DS#revert` somewhere, and make a new PR from a new branch.

**Comment by internalfx** [comment]
Agreed, I think feature branches are what I really need to be doing...

There's got to be a way to not constantly screw everything up, I feel like I never really know what git is about to do when I run certain commands.

It's time to take a day or two and really learn git.

**Comment by internalfx** [comment]
OK, I'm gonna blow out my whole repo.

And send a clean PR.

**Pull request closed without merging**
