### PR TITLE
Closes #243. Dropped Grunt.

### LINKED ISSUE #243: DS#commit
Initial implementation:

```javascript
commit (resourceName, id) {
  let {_this, definition, _resourceName, _id} = check.call(this, 'commit', resourceName, id)
  let resource = _this.store[_resourceName]
  let item = _this.store[_resourceName].index[_id]
  if (item) {
    resource.previousAttributes[_id] = DSUtils.copy(item, null, null, null, definition.relationFields)
  }

  if (resource.changeHistories[_id].length) {
    DSUtils.forEach(resource.changeHistories[_id], function (changeRecord) {
      DSUtils.remove(resource.changeHistory, changeRecord)
    })
    resource.changeHistories[_id].splice(0, resource.changeHistories[_id].length)
  }
  return item
}
```

### PR DESCRIPTION
**Pull request by jmdobry**
Closes #243

### CODE REVIEW

**Comment by internalfx** [comment]
Is js-data using gulp now?

Don't see it in the deps...

**Comment by jmdobry** [comment]
https://github.com/js-data/js-data/pull/244/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R63

**Comment by internalfx** [comment]
Doing it the hard way eh?

You know it has never even crossed my mind to just *not* use a build system.

**Comment by internalfx** [comment]
@jmdobry any Idea when this will merge?

Just pulled upstream....

**Comment by jmdobry** [comment]
I'm at work, so tonight. Would you like write access?

**Comment by internalfx** [comment]
Let's chat tonight, I was thinking of approaching my employer about donating some of my time to the project.

**Comment by jmdobry** [comment]
Let's hope I don't get hit by a bus before tonight...

**Comment by internalfx** [comment]
I think it's best for the project if you don't ride a bus...or a bike...or a motorcycle.

Just drive a giant SUV to work, ok? :smile:

**Pull request merged**
