### PR TITLE
fix(utils): deepMixIn to properly merge undefined values of source

### LINKED ISSUE #501: deepMixIn merges in source properties that resolve to undefined into dest
## Description

`deepMixIn` merges in `src` properties that resolve to `undefined` into `dest` even if they have a value in `dest`

## Steps to reproduce
```js
const dest = { name: 'John', age: 90 }
const src = { name: 'John', age: undefined }
const expected = { name: 'John', age: 90 }
utils.deepMixIn(dest, src) // results to { name: 'John' }
```

Thanks!

### PR DESCRIPTION
**Pull request by ivanvoznyakovsky**
Fixes #501

- [x] - `npm test` succeeds
- [x] - Code coverage does not decrease (if any source code was changed)
- [ ] - If applicable, appropriate JSDoc comments were updated in source code (if applicable)
- [ ] - If applicable, approprate changes to js-data.io docs have been suggested ("Suggest Edits" button)

### CODE REVIEW

**Comment by zuzusik** [comment]
this new behavior should be somehow optional

in some cases it can be required to remove properties that don't exist anymore - e.g. some prop was removed from the object and we receive updated object from the network

**Comment by ivanvoznyakovsky** [comment]
isn't `onConflict` config option is what you're talking about? setting it to `replace` would actually do what you describe and this change fixes the default `merge` strategy. 
but anyway I do hear what you say and this change should definitely be marked as `breaking change` since it can break some code that actually relied on buggy `merge` strategy.

**Comment by crobinson42** [comment]
@zuzusik I think you might be right - this could cause potential breaking behavior in existing implementations. I'll look at possibly making this an option with some flag. If you have any ideas, throw them out.

**Comment by crobinson42** [comment]
@ivanvoznyakovsky `onConflict` only applies to one use of `deepMixin()` in `Collection.js`, inside `Record.js` the `save()` method also uses `deepMixin()` without `onConflict`.

**Comment by ivanvoznyakovsky** [comment]
@crobinson42 I should have missed it. then we should definitely think of making it optional.

**Comment by crobinson42** [comment]
After looking at at example a little further and taking into consideration @zuzusik comment about this breaking existing implementations - the code snippet in the issue doesn't correctly depict the behavior, @ivanvoznyakovsky - the key still exists but is overwritten with the value `undefined`. I'm going to lean towards maintaining the `deepMixin()` existing behavior.

**Comment by crobinson42** [comment]
@ivanvoznyakovsky here is an example of the existing behavior without this PR: https://runkit.com/crobinson42/github-com-js-data-js-data-issues-501

**Comment by ivanvoznyakovsky** [comment]
actual problem is how record object is created from api response based on record schema.
say we have the following schema for a record
```js
{
  schema: {
    properties: {
      uid: {type: 'string'},
      name: {type: 'string'}, 
      comment: {type: 'string', 'null'}
    }
  }
}
```
`comment` is only returned when queried explicitly with a url param, say `withComment`.
now there are 2 components that make 2 requests in parallel. one does a request with `withComment` param the other one does not need a `comment` hence skips `withComment` param. 
if a request that was done without `withComment` param resolves after the one with `withComment` we'll get in the following situation:
- the record is created from response data `{uid: 1, name: 'some'}` based on schema `{uid: 1, name: 'some', comment: undefined}`
- this record is merged with the one in store, eg. `{uid: 1, name: 'some', comment: 'a comment'}`, resulting in store record `{uid: 1, name: 'some', comment: undefined}`
- component that requires `comment` field now fails to show it although it requested it and it was in the response.
this is the exact problem we're facing in our app.

**Comment by ivanvoznyakovsky** [comment]
as @zuzusik said we could potentially make skipping `undefined` fields of source optional. say having a config option `skipUndefinedOnMerge` that is `false` by default. which would be the same as it is now.

**Comment by crobinson42** [comment]
@ivanvoznyakovsky I understand your situation - thanks for outlining that. I don't disagree with making a flag to skip `undefined` fields. If you've got some ideas on how to integrate that cleanly, throw them out :-)

**Comment by ivanvoznyakovsky** [comment]
thoughts on creating a new merge strategy `mergeSkipUndefined`? we'll still keep `merge` as default one but could just override it when needed like via `onConflict` value. 
`deepMixIn` would get a 3rd param `skipUndefined`.

**Comment by crobinson42** [comment]
I think the problem is in the way the schema is applied - perhaps we should look at a different angle of solving this. 

I don't think the situation you described above where a query is made without explicitly defining a key, then that key shouldn't be in the source object to be merged, ie: if `withComment` isn't defined, there should not be a key at all in the object.

**Pull request merged**
