### PR TITLE
Call reapAction if it is a function

### PR DESCRIPTION
**Pull request by ostcar**
It would be nice to define a function that is called on reap.

### CODE REVIEW

**Comment by jmdobry** [comment]
Makes sense, though it seems quite redundant if you can just do `reapAction: 'none'` and define a [beforeReap](http://www.js-data.io/v1.3.0/docs/dsdefaults#beforereap) and/or [afterReap](http://www.js-data.io/v1.3.0/docs/dsdefaults#afterreap) function.

**Comment by ostcar** [comment]
I tried this but it did not work.
My goal is to keep the old objects in the datastore but fetch them from the adapter the next time they are requested. I did this with:
```javascript
reapAction: function(resource, items) {
    _.forEach(items, function(item) {
        delete resource.completedQueries[item.id];
    });
},
```
The argument ```resource``` from ```beforeReap``` does not contain the dictionary ```completedQueries```. 
Maybe this could be changed.

**Comment by jmdobry** [comment]
```js
var store = new JSData.DS();

store.defineResource({
  name: 'user',
  maxAge: 900000,
  reapInterval: 30000,
  reapAction: 'none',
  afterReap: function (User, users) {
    _.forEach(users, function(user) {
        delete store.store[User.name].completedQueries[user.id];
    });
  }
});
```

**Comment by ostcar** [comment]
Thanks! Next time I ask before I create a pull request ;)

**Pull request closed without merging**
