### PR TITLE
Add the ability to define the relationName in a relation

### PR DESCRIPTION
**Pull request by davidpp**
Allow the ability to specify a custom relationName.  For example :

```coffeescript
relations:
  belongsTo:
   arena:
     localField: 'arena'
     localKey: 'arenaId'
   awayTeam:
     localField: 'awayTeam'
     localKey: 'awayTeamId'
     relationName: 'team'
   homeTeam:
     localField: 'homeTeam'
     localKey: 'homeTeamId'
     relationName: 'team'
```

### CODE REVIEW

**Comment by davidpp** [comment]
It's probably missing the required test.  I haven't had time to take a look at those, but gitter is down and still wanted to push it so that you knew I was working on it.

**Comment by jmdobry** [comment]
Interesting. The current way of having multiple relations to a particular resource is to use an array:

```coffeescript
relations: {
  belongsTo: {
    arena: {
      localField: 'arena'
      localKey: 'arenaId'
    },
    team: [
      {
        localField: 'awayTeam'
        localKey: 'awayTeamId'
      },
      {
        localField: 'homeTeam'
        localKey: 'homeTeamId'
      }
    ]
  }
}
```

and then you can do:

```javascript
.loadRelations(1, ['arena', 'awayTeam'])
.loadRelations(1, ['arena', 'homeTeam'])
// etc.
```

Your different approach is interesting, but the implementation is incomplete. There are a few more places in the code that would need the `typeof def.relationName !== 'undefined' ? def.relationName : def.relation;` fix

**Comment by davidpp** [comment]
Just pushed another commit I think I covered them all? To be honest, I didn't know I could do that this way. In Rails they work a bit like what I did if I remember correctly, so I'm a bit used to have named relationship.

**Comment by jmdobry** [comment]
K, now gonna need some tests. And all the adapters but the http adapter will need to be updated to support `relationName` as well.

**Comment by davidpp** [comment]
Doing a quick follow-up on this, have you had time to think about it a bit ?

**Comment by jmdobry** [comment]
@davidapp Now that you know that you can use arrays to specify multiple relations to a single resource type, does it really make sense to add this?

**Comment by davidpp** [comment]
What I prefer about this approach is that the API is the same regardless if the document is embedded or is a relation.  Unless I'm missing something?

Example : 
```
org = Organization.find(1)
org.managers // can either normalized or denormalized depending on perf requirement / audit etc.
org.employees

**Comment by jmdobry** [comment]
I don't follow, can you post a more complicated example?

**Comment by davidpp** [comment]
My bad, was away for a few days and replied before I was fully back into dev mode.  I can do the same thing with the array version of the definition. Closing the PR

**Comment by jmdobry** [comment]
Thanks for the contribution though!

**Pull request closed without merging**
