### PR TITLE
Extract Descriptor creation to RelationDescriptorFactory in Descriptor.js

### PR DESCRIPTION
**Pull request by pik**
- Created a class for each Descriptor: HasManyRelationDescriptor, BelongsToRelationDescriptor, HasOneRelationDescriptor.

Large but simple refactor which should help with a lot of other things, especially making it easier to implement and review changes to the existing code. TODO:
- [ ] Reduce code reduplication by extending all Descriptors from a base Class 
- [ ] Add code comments for documentation to make Descriptor functionality clear, also Relation tutorial for 3.0

A slight drawback might be that there is some reduplicate constant declaration due to the context -- probably this is not bad a thing since it is after all safer to be working in a narrower scope.

### CODE REVIEW

**Comment by jmdobry** [comment]
Tests fail in PhantomJS, I'm guessing because of the use of `class` syntax. If JSData were solely a Node.js project, then I would have used the `class` syntax throughout the code, but it needs to play nicely with ES5 browsers and TypeScript, and the way Babel transpiles `class` into ES5 isn't always friendly.

I'd recommend switching to plain functions to define the classes, e.g.

```
function BelongsToRelationDescriptor (store, mapper, collection, def) {
  // ...
}
```

Instead of classes, a better approach would actually be to add `addDescriptor` methods to the 3 relation classes found in `src/Relation/`. Instead of the `RelationDescriptorFactory` with its `if (...) else if (..)` you would simply have:

```js
mapper.relationList.forEach(function (def) {
  def.addDescriptor(store, mapper, collection)
})
```

The common stuff needed by all 3 relation classes can go on the `addDescriptor` of the base `Relation` class.

**Comment by stalniy** [comment]
@jmdobry @pik guys I see it in a bit different way:
* `addDescriptorOf(relationType)` should be a method of `DataStore`
* the whole method looks like: 
```js
addDescriptorOf (relationType) {
  Object.defineProperty(relationType.mapper.recordClass.prototype, relationType.localField, {
    get() {
       return relationType.getRelatedRecords(this)
    },

    set(records) {
       relationType.associateRelatedRecordsWith(this, records)
    }
  })
}
```
I believe this will look more readable and straightforward. I almost finished with refactoring of `Mapper.js` file. So, when I push PR with Mapper.js it will be much easier to see the whole picture

**Comment by pik** [comment]
@stalniy Except the reason for the functions being dynamically declared is that `get()` `set()` will bind `this` to the target of `defineProperty` so you need to have at least `(store, mapper, collection, def)` available in the scope of the `setter()` / `getter()`. 

Do you have a branch  / commit we could look at ?

**Comment by pik** [comment]
@jmdobry I pushed an update with your suggested structure - although I do think @stalniy's idea is pretty good also - I'm just not sure how to make it look nice atm (maybe we can do foreignKey `set()` without chaining?). 

At any rate I don't have a strong opinion on the interface but extracting the code should make it quite a bit easier to work with.

**Comment by jmdobry** [comment]
@stalniy's idea does make sense, but I think this way the code might be a little more reusable. Let's see what his Mapper.js PR looks like.

**Comment by crobinson42** [comment]
Closing - this PR code is outdated for the current codebase.

**Pull request closed without merging**
