### PR TITLE
Allow resource instances to be created from a base class

### PR DESCRIPTION
**Pull request by mhwinkler**
Per the discussion here: https://groups.io/org/groupsio/jsdata/thread/33314

Instead of useClass being a simple boolean operator, I would suggest we allow for two data types to be passed: boolean yes/no (for a generic constructor) or a function (for our new constructor to inherit from).

In this way, instances of models would be able to inherit the properties and behavior of a given base model, rather than just being supplied with individual helpers via the methods: config.

### CODE REVIEW

**Comment by mhwinkler** [comment]
Sorry - I thought that this solution would fail minification, but it appears to be passing just fine.

**Comment by jmdobry** [comment]
So far as I know, `eval` is the only way to create a named function at runtime, rather than at parse time.

Instead of
```js
var useClass = def.useClass;
eval('function ' + def['class'] + '() { useClass.call(this); }');
```
can't you just do
```js
eval('function ' + def['class'] + '() { def.useClass.call(this); }');
```

**Comment by mhwinkler** [comment]
I'm really unfamiliar with `eval` and how it works with minification so I'm assuming you are correct there. I think I was being overly explicit in my testing.

**Comment by jessemorton** [comment]
It seems that the ability to use a base class may affect some other areas of JSData. For example, when I have some properties defined on my custom base class, those are showing up within the DSHasChanges() object's  `added`, causing a false positive that there's changes.

**Comment by jmdobry** [comment]
@jessemorton Perhaps open an issue or post on the mailing list with more information: versions, code examples, etc. 

These are "static" properties attached to your base constructor function?

**Comment by jessemorton** [comment]
Opened a new issue. Let me know if I can provide more information or the like.

**Pull request merged**
