### PR TITLE
Adding case insensitive filtering in query syntax

### PR DESCRIPTION
**Pull request by mapsi**
My first ever PR, be kind to me! :smile:

### CODE REVIEW

**Comment by jmdobry** [comment]
js-data-sql has a like operator, if this is also going to be a "like" then it should probably have the same behavior of a sql like. I'll have to verify what that is exactly.

**Comment by mapsi** [comment]
Apart from the operator name, does it look ok? I could rename it to whatever works best for you and create a new PR. Ta!

**Comment by jmdobry** [comment]
First ever PR! Congrats.

But, `if (DSUtils._s(val)) {` tests to see if `val` is a string. If `val` is not a string, then the `else` case will be hit, and if `val` is not a string, then you can't just call `.toUpperCase()` on `val`. So that's not going to work.

I'm not sure exactly how this should be handled. Another way that I was planning on supporting case-insensitivity was to allow regular expressions as the term. I'll think about this more.

**Comment by mapsi** [comment]
Hey @jmdobry, have you had any thoughts about this one?
The check has failed due to "timeout of 2000ms exceeded."

**Comment by jmdobry** [comment]
Nope, don't have internet at my house yet, and not done painting yet, which all kinda gets in the way of spending free time on open source. I'll get to it, I promise.

**Comment by jmdobry** [comment]
Closing in favor of https://github.com/js-data/js-data/commit/3b87fe885ab8792956497b6f47250a75f4a2d1d3

**Pull request closed without merging**
