### PR TITLE
add get property by function

### PR DESCRIPTION
**Pull request by muchrm**

### CODE REVIEW

**Comment by crobinson42** [comment]
@muchrm can you help me understand this PR and why it might be needed?

**Comment by kvandelden** [comment]
Not sure what the author's intent, but we have run into this..  Under high CPU utilization of the getter (also setter), the split function becomes the performance bottleneck.. this would provide a means to avoid the split function.

**Comment by crobinson42** [comment]
@kvandelden Interesting.. that hadn't occurred to me. Where in the js-data code base would a user be able to take advantage of this `get()` util method? Maybe i'm not fully understanding the use case here 🤷🏼‍♂️

**Comment by muchrm** [comment]
@crobinson42 this PR help me to place custom logic to get property in order by
example: 
if (model.date_create > current_date){
  return 1;
} else {
  return -1;
}

if it's not help anyone you can close this PR.
sorry for my skill conversation.
thank

**Comment by kvandelden** [comment]
I'm not suggesting this is the best route to solving the performance issue.. but it could be used when overriding the Schema's makeDescriptor
image

 We have overridden makeDescriptor to improve the property set performance... and change the tracking behavior.

1. If a property is changed from it's original value to a new value and then back..  we still fire the change event.
image

2. Fast path for property setting
image

  Instead of calling _set with (  `props.${prop}` ), that requires the array split, we avoid the split by calling _setProps, which will only set values in the props object. .. but avoids the split penalty.

**Pull request closed without merging**
